export const LOAD_INSPECTIONS_SUCCESS = "LOAD_INSPECTIONS_SUCCESS";
export const LOAD_INSPECTIONS_FAILURE = "LOAD_INSPECTIONS_FAILURE";
export const LOAD_INSPECTIONS_PENDING = "LOAD_INSPECTIONS_PENDING";

export const LOAD_INSPECTION_SUCCESS = "LOAD_INSPECTION_SUCCESS";
export const LOAD_INSPECTION_FAILURE = "LOAD_INSPECTION_FAILURE";
export const LOAD_INSPECTION_PENDING = "LOAD_INSPECTION_PENDING";

export const ADD_INSPECTION_SUCCESS = "ADD_INSPECTION_SUCCESS";
export const ADD_INSPECTION_FAILURE = "ADD_INSPECTION_FAILURE";
export const ADD_INSPECTION_PENDING = "ADD_INSPECTION_PENDING";

export const DELETE_INSPECTION_SUCCESS = "DELETE_INSPECTION_SUCCESS";
export const DELETE_INSPECTION_FAILURE = "DELETE_INSPECTION_FAILURE";
export const DELETE_INSPECTION_PENDING = "DELETE_INSPECTION_PENDING";

export const EDIT_INSPECTION_SUCCESS = "EDIT_INSPECTION_SUCCESS";
export const EDIT_INSPECTION_FAILURE = "EDIT_INSPECTION_FAILURE";
export const EDIT_INSPECTION_PENDING = "EDIT_INSPECTION_PENDING";

export const LOAD_MEMBERS_SUCCESS = "LOAD_MEMBERS_SUCCESS";
export const LOAD_MEMBERS_FAILURE = "LOAD_MEMBERS_FAILURE";
export const LOAD_MEMBERS_PENDING = "LOAD_MEMBERS_PENDING";

export const LOAD_MEMBER_SUCCESS = "LOAD_MEMBER_SUCCESS";
export const LOAD_MEMBER_FAILURE = "LOAD_MEMBER_FAILURE";
export const LOAD_MEMBER_PENDING = "LOAD_MEMBER_PENDING";
